// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: restaurant.proto

package restaurant_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int64                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuRequest) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenuResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *MenuItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateMenuItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   int64                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	ProductId      int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	NewPrice       *int64                 `protobuf:"varint,3,opt,name=new_price,json=newPrice,proto3,oneof" json:"new_price,omitempty"`
	NewDescription *string                `protobuf:"bytes,4,opt,name=new_description,json=newDescription,proto3,oneof" json:"new_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	mi := &file_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMenuItemRequest) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetNewPrice() int64 {
	if x != nil && x.NewPrice != nil {
		return *x.NewPrice
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetNewDescription() string {
	if x != nil && x.NewDescription != nil {
		return *x.NewDescription
	}
	return ""
}

type UpdateMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemResponse) Reset() {
	*x = UpdateMenuItemResponse{}
	mi := &file_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemResponse) ProtoMessage() {}

func (x *UpdateMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMenuItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateMenuItemResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_restaurant_proto protoreflect.FileDescriptor

const file_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x10restaurant.proto\x12\rrestaurant_v1\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x0eGetMenuRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x03R\frestaurantId\"@\n" +
	"\x0fGetMenuResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.restaurant_v1.MenuItemR\x05items\"u\n" +
	"\bMenuItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\"\xcd\x01\n" +
	"\x15UpdateMenuItemRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x03R\frestaurantId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12 \n" +
	"\tnew_price\x18\x03 \x01(\x03H\x00R\bnewPrice\x88\x01\x01\x12,\n" +
	"\x0fnew_description\x18\x04 \x01(\tH\x01R\x0enewDescription\x88\x01\x01B\f\n" +
	"\n" +
	"_new_priceB\x12\n" +
	"\x10_new_description\"m\n" +
	"\x16UpdateMenuItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xbc\x01\n" +
	"\x11RestaurantService\x12H\n" +
	"\aGetMenu\x12\x1d.restaurant_v1.GetMenuRequest\x1a\x1e.restaurant_v1.GetMenuResponse\x12]\n" +
	"\x0eUpdateMenuItem\x12$.restaurant_v1.UpdateMenuItemRequest\x1a%.restaurant_v1.UpdateMenuItemResponseBXZVgithub.com/Wuchinator/food-delivery/restaurant-service/pkg/restaurant_v1;restaurant_v1b\x06proto3"

var (
	file_restaurant_proto_rawDescOnce sync.Once
	file_restaurant_proto_rawDescData []byte
)

func file_restaurant_proto_rawDescGZIP() []byte {
	file_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)))
	})
	return file_restaurant_proto_rawDescData
}

var file_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_restaurant_proto_goTypes = []any{
	(*GetMenuRequest)(nil),         // 0: restaurant_v1.GetMenuRequest
	(*GetMenuResponse)(nil),        // 1: restaurant_v1.GetMenuResponse
	(*MenuItem)(nil),               // 2: restaurant_v1.MenuItem
	(*UpdateMenuItemRequest)(nil),  // 3: restaurant_v1.UpdateMenuItemRequest
	(*UpdateMenuItemResponse)(nil), // 4: restaurant_v1.UpdateMenuItemResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_restaurant_proto_depIdxs = []int32{
	2, // 0: restaurant_v1.GetMenuResponse.items:type_name -> restaurant_v1.MenuItem
	5, // 1: restaurant_v1.UpdateMenuItemResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: restaurant_v1.RestaurantService.GetMenu:input_type -> restaurant_v1.GetMenuRequest
	3, // 3: restaurant_v1.RestaurantService.UpdateMenuItem:input_type -> restaurant_v1.UpdateMenuItemRequest
	1, // 4: restaurant_v1.RestaurantService.GetMenu:output_type -> restaurant_v1.GetMenuResponse
	4, // 5: restaurant_v1.RestaurantService.UpdateMenuItem:output_type -> restaurant_v1.UpdateMenuItemResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_restaurant_proto_init() }
func file_restaurant_proto_init() {
	if File_restaurant_proto != nil {
		return
	}
	file_restaurant_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurant_proto_msgTypes,
	}.Build()
	File_restaurant_proto = out.File
	file_restaurant_proto_goTypes = nil
	file_restaurant_proto_depIdxs = nil
}
